### ISSUE TITLE
API docs are not rendering

### ISSUE THREAD

**Issue by jenweber** [glimmerjs/glimmer-website#103]
The API docs simply don't show up. It was reported in the Slack help channel. Confirmed in Chrome, Firefox, and Safari. No errors in the console.

![screen shot 2017-11-11 at 2 11 56 pm](https://user-images.githubusercontent.com/16627268/32692679-7caf2f96-c6ea-11e7-9cfd-23e6ec2c5938.png)

**Comment by locks** [comment]
Fixed. We'll see how permanently :x
