### ISSUE TITLE
jQuery is used in docs without being imported

### ISSUE THREAD

**Issue by Alonski** [glimmerjs/glimmer-website#111]
https://github.com/glimmerjs/glimmer-website/blob/master/src/guides/components-and-actions.md

At the bottom `$` is used without being installed and imported. This causes runtime errors.

```
import Component from '@glimmer/component';

export default class extends Component {
  didInsertElement() {
    $(this.element).pickadate();
  }
}
```

**Comment by jakeonfire** [comment]
solution is not to import it, but to install the jquery type. first:
```bash
yarn add @types/jquery --dev
```
then in `tsconfig.json`:
```json
"compilerOptions": {
  ...
  "types": [
    "jquery", // add this
    "qunit"
  ]
}
```

**Comment by Alonski** [comment]
@jakeonfire After doing this I can use it globally? Why not import it?
