### ISSUE TITLE
Documentation should use 'this' for component property access

### ISSUE THREAD

**Issue by bbarkley** [glimmerjs/glimmer-website#117]
In https://emberjs.github.io/rfcs/0308-deprecate-property-lookup-fallback.html the recommendation is for component templates to use the "this" prefix when referencing component properties. The current docs don't follow this convention.

**Comment by rwjblue** [comment]
Thanks for opening this issue! You are absolutely correct, we should migrate to avoid using the property lookup fallback. We'd love help if someone has time to review the current docs and send in a PR...
