### ISSUE TITLE
API doc missing

### ISSUE THREAD

**Issue by Herriau** [glimmerjs/glimmer-website#132]
Navigating to [https://glimmerjs.com/api/](https://glimmerjs.com/api/) gives a 404 error. As of writing this is the first result I get when I google "glimmerjs api".

Navigating to [https://glimmerjs.com/](https://glimmerjs.com/), I no longer see a link to the API doc.

The closest to an API doc I was able to get my hands on is at [https://api.emberjs.com/ember/release/modules/@glimmer%2Fcomponent](https://api.emberjs.com/ember/release/modules/@glimmer%2Fcomponent), but it's not as detailed as what used to be on the GlimmerJS website.

**Comment by nummi** [comment]
@Herriau,

The docs were recently removed: https://github.com/glimmerjs/glimmer-website/pull/131

**Comment by Herriau** [comment]
Is it safe to say that GlimmerJS is no longer blessed for standalone usage?
