### ISSUE TITLE
Cover the use of util files in components

### ISSUE THREAD

**Issue by acorncom** [glimmerjs/glimmer-website#17]
And an explanation of where they go.  Probably worth putting in the components page?

**Comment by acorncom** [comment]
They need to be regular `.ts` files (in `src/utils/`) that we import using relative paths.  `.js` files aren't currently supported by the blueprints, but will be soon ...

**Comment by acorncom** [comment]
We should also mention the other place it can be put:

`app/src/ui/my-component/-utils/load-me.ts`

**Comment by Etromania** [comment]
Please do and show how to import it into a component.ts file. It's a huge turn off when you have to jump through hoops to figure out how to do something as simple as import a util file.

**Comment by oligriffiths** [comment]
Can we get an example here for how to use utils at least?

Thanks
