### ISSUE TITLE
Document CSS options

### ISSUE THREAD

**Issue by acorncom** [glimmerjs/glimmer-website#23]
We support either SASS or will concatenate CSS: https://github.com/glimmerjs/glimmer-application-pipeline/pull/35

**Comment by jessica-jordan** [comment]
@acorncom I haven't contributed to this project before, but would like to. Could the additional documentation simply be an extension of the `Styles` section at https://glimmerjs.com/guides/filesystem-layout ? I'm happy to throw a PR for that

**Comment by locks** [comment]
@jessica-jordan 👍 I think is the medium-term we will want a dedicated styles guide, when we get colocated CSS, but that should be enough for now.
