### ISSUE TITLE
Seeking Glimmer Guides Clarity

### ISSUE THREAD

**Issue by jwithington** [glimmerjs/glimmer-website#31]
Brand newbie (to Ember, and Glimmer) looking for clarity in the guides.  Some things that happened on my first pass through the Glimmer guides today:

- The tree for my project didn’t match what the guides had (including omitting a styles folder), though I didn’t notice until a bit after the fact. After uninstalling yarn and also ember-cli (someone in the announcements channel suggested that second one, if folks were using yarn), I *was* able to get the tree to match. 

- In File System Layout, it references `hello-again`, though the earlier step created `hello-portland`.

- in Templates and helpers, there seems to be a need to be a closing tag for `<conference-speaker @name="Tom" @status="Speaking">`. Until I added one, my localhost was telling me the build failed.

- In general, the guides don’t explain where to put code for the different components as they are being built, in order to not break the build. For example: 
	> This then allows us to use that component as a top-level component in our my-app/template.hbs file:
<hello-again />

In the context of the guides, does that mean I should put `<hello-portland />` in the my-app/template.hbs file? This is one example, but this happens with conference-speaker as well.  I found myself throwing different tags like `<hello-portland />`  and `<conference-speaker />` in different files just to see if I could get it to work. My attempts end up breaking the build, making the screen appear white, or having it continue to say “Welcome to Glimmer.” The last one sorta feels successful, as it means I figured out how I broke it -- but learning where to put these things would be even better. 😄 

This should not at all read as complaining — I just thought, “hey, you likely don’t get brand newbies that can report things like this very often,” and figured it would help. I was stoked to try this out as my first attempt in the Emberverse — especially after this morning’s talks — but the guides aren’t enough to address the newbie ramp up yet. I hope this helps!  😃

**Comment by acorncom** [comment]
Hey @jwithington, appreciate the feedback!  The hitlist is quite useful. The guides for Glimmer were written pretty quickly and didn't get much review.  So we'll definitely take a look at things and clean it up. Thanks 😀

**Comment by jwithington** [comment]
@acorncom heck yes! Awesome! Let me know if I can help. 😀

**Comment by acorncom** [comment]
@jwithington Would you mind checking the things you mention above again?  Based on a quick review, I **think** most of those issues have been fixed in small PRs in the last day.  Could you confirm?

**Comment by jwithington** [comment]
@acorncom absolutely! I'm on a volunteering shift now, but will get to it ASAP.

**Comment by jwithington** [comment]
Awesome: I got a lot further in this, and in fact worked through it all the way up to the Using Glimmer as Web Components portion. It's looking good. 

So, hitlist, with update:

- [ ] The tree for my project didn’t match what the guides had. 

This is still true, in a different way; see below

- [X] In File System Layout, it references hello-again

- [X] In Templates and helpers, there seems to be a need to be a closing tag for <conference-speaker @name="Tom" @status="Speaking">

- [ ] In general, the guides don’t explain where to put code for the different components as they are being built, in order to not break the build. 

This has improved a bunch, and when I experimented with adding <conference-speaker />, the guide made it easy to understand where it would break and where it wouldn’t. 😄 Example: I got Tom is Speaking to appear even though it didn’t explicitly mention to try that. 

Some more things:

- In [Getting Started](https://glimmerjs.com/guides/getting-started), when I created the new app, my list of “create” included ` create src/ui/styles/app.scss` as you see below,.  That’s not listed in the guide
>  … snipped …
  create src/ui/components/my-app/component.ts
  create src/ui/components/my-app/template.hbs
  create src/ui/index.html
  create src/ui/styles/app.scss
  
- The app tree in [Filesystem Layout](https://glimmerjs.com/guides/filesystem-layout) (and perhaps elsewhere) includes `ui/components/hello-glimmer`, which isn’t actually part of the components that the tutorial creates, so that’s still not quite accurate (perhaps an artifact of an earlier version?)

- We should probably explicitly state where ` console.log(this.args.name);` should go (which component) in [Templates and helpers](https://glimmerjs.com/guides/templates-and-helpers). Right now that’s a bit unclear. Just below that, it’s much clearer, and “Hello, Robbie” has the context needed to make it so. 

- The explanation “We know that @firstName came from the parent component, not the current component, because it starts with @ and is therefore an argument.” confused me a bit, because we just made @name={{user.name}}  — and @name there doesn’t relate to the parent component (or does it?). 

- in the Lifecycle Hooks section of [Components and Actions](https://glimmerjs.com/guides/components-and-actions), there’s an example that talks about including a jQuery plugin. It’s unclear where to put that code if I wanted to use it; I tried placing it within the same component as we discussed earlier in the page, and I got a build error.  

- In general, the tutorial examples are a bit confusing because of `conference-speakers` and `conference-speaker` looking so similar. That might just be personal taste.  I also think that all (not just some) code examples would really benefit from having the file path directly above them (which seems to start appearing in [Components and Actions(https://glimmerjs.com/guides/components-and-actions)

If I find anything as I complete the last two sections, I'll open a new issue. 👍
