### ISSUE TITLE
Ensure it is clear at a glance to non-Ember devs that Ember is not required

### ISSUE THREAD

**Issue by localpcguy** [glimmerjs/glimmer-website#41]
Common refrain I read after the announcement of Glimmer was that (non-Ember) devs went to the site, saw Ember / Ember-CLI and got the impression that Glimmer runs on top of Ember. The site homepage should make this explicitly clear that this is a stand-alone library that, while it uses the Ember-CLI, does not require Ember itself at all. It should be clear without people watching the video.

I'm happy to try my hand at a few small edits to the home page copy to make this clear.

**Comment by wycats** [comment]
@localpcguy go for it!
