### ISSUE TITLE
regenratorRuntime undefined. Glimmer intro suggests async/await works out of the box. 

### ISSUE THREAD

**Issue by WillsonSmith** [glimmerjs/glimmer-website#43]
In the [Glimmer intro video](https://www.youtube.com/watch?v=i2rwIApjz-4) it seems to suggest that you can just use async/await out of the box without setup. Unfortunately when you try to use async/await you get errors where `regeneratorRuntime` is undefined.

Safari: `ReferenceError: Can't find variable: regeneratorRuntime`
Chrome: `Uncaught ReferenceError: regeneratorRuntime is not defined`

It would be nice if there was explanation as to how to set this up, or, if this is a bug with Glimmer, perhaps an issue should be opened on its repository. I think the video is causing some confusion as it is right now. 

Perhaps this may be covered as the API docs are expanded.

**Comment by locks** [comment]
@WillsonSmith hi, did you create your project with the web component option on?

**Comment by NotGrm** [comment]
Thanks @locks for the tip !

I've just added `@glimmer/web-component` to my **package.json** and async/await is now working on my project

**Comment by dgeb** [comment]
Thanks to @migbar for documenting this via #46.

We should also be able to make this work by opting into ES2017 builds instead of transpiling down to ES5, although there are obvious compatibility tradeoffs. Regardless, we should provide the option.

**Comment by WillsonSmith** [comment]
💯 awesome, thanks for adding this to the docs @migbar. I think this can be closed now.

**Comment by alvincrespo** [comment]
I just tried this and the solution mentioned in the docs doesn't work for me. Even when going through the guide and creating a new app with the web-component flag:

```
ember new display-tile -b @glimmer/blueprint --web-component
```

Curious what does the magic here?

This is my environment FYI: 

```
➜  display-tile git:(master) ✗ ember -v
ember-cli: 2.13.0-beta.3
node: 7.8.0
os: darwin x64
➜  display-tile git:(master) ✗
```

**Comment by calderas** [comment]
I'm also having this issue:

```
ember-cli: 2.13.0-beta.3
node: 7.9.0
os: darwin x64
```

```
"@glimmer/application": "^0.4.0",
    "@glimmer/application-pipeline": "^0.6.0-beta.2",
    "@glimmer/blueprint": "^0.1.12",
    "@glimmer/component": "^0.3.8",
    "@glimmer/resolver": "^0.3.0",
    "@glimmer/web-component": "^0.1.2",
    "broccoli-asset-rev": "^2.5.0",
    "ember-cli": "github:ember-cli/ember-cli",
    "ember-cli-inject-live-reload": "^1.6.1",
    "ember-cli-uglify": "^1.2.0",
    "typescript": "^2.2.2"
```

**Comment by WillsonSmith** [comment]
Just tried creating a new app, and as stated above it seems this is no longer working by using the `--web-component` argument.

Going to reopen this, could be a regression?

**Comment by moilopez** [comment]
Same issue with me

`ember-cli: 2.13.0-beta.4
node: 6.9.2
os: darwin x64`

`    "@glimmer/application": "^0.4.0",
    "@glimmer/application-pipeline": "^0.6.0-beta.2",
    "@glimmer/blueprint": "^0.1.12",
    "@glimmer/component": "^0.3.8",
    "@glimmer/resolver": "^0.3.0",
    "@glimmer/web-component": "^0.1.2",
    "broccoli-asset-rev": "^2.5.0",
    "ember-cli": "github:ember-cli/ember-cli",
    "ember-cli-inject-live-reload": "^1.6.1",
    "ember-cli-uglify": "^1.2.0",
    "typescript": "^2.2.2"`

**Comment by robbiepitts** [comment]
@WillsonSmith Not a regression, definitely still a problem though. See https://github.com/glimmerjs/glimmer-website/issues/62#issuecomment-295753360

**Comment by mhadaily** [comment]
I just wanna send mine, hopefully that may help. 

````
Tried with : npm install -g ember-cli@2.14.0-beta.1

->  Uncaught ReferenceError: regeneratorRuntime is not defined

 "devDependencies": {
        "@glimmer/application": "^0.4.0",
        "@glimmer/application-pipeline": "^0.6.0-beta.2",
        "@glimmer/blueprint": "^0.2.1",
        "@glimmer/component": "^0.3.8",
        "@glimmer/resolver": "^0.3.0",
        "broccoli-asset-rev": "^2.5.0",
        "ember-cli": "github:ember-cli/ember-cli",
        "ember-cli-inject-live-reload": "^1.6.1",
        "ember-cli-uglify": "^1.2.0",
        "typescript": "^2.3.3"
    },
````

**Comment by locks** [comment]
Instructions now at https://github.com/glimmerjs/glimmer-application-pipeline#enabling-use-of-async-await-in-components.
