### ISSUE TITLE
Document how to create a tracked computed property based on arguments

### ISSUE THREAD

**Issue by courajs** [glimmerjs/glimmer-website#49]
I tried `@tracked('@somearg')` and `@tracked('args.somearg')` and neither seemed to work. Do I have to use a lifecycle hook and assign it to an internal property?

**Comment by locks** [comment]
`tracked` does not support paths yet, that would be why. I don't think you have a useful lifecycle hook either, for now :P

**Comment by courajs** [comment]
In the meantime, something like this does work.
```js
import Component, { tracked } from '@glimmer/component';
export default class AstCompiler extends Component {
  @tracked computed = ""
  didInsertElement() { this.compute() }
  didUpdate() { this.compute() }
  compute() { this.computed = 'abc' + this.args.prop }
};
```

**Comment by locks** [comment]
I know this isn't quite what you want @courajs, but for now you can do `@tracked('args')` and it will update when one of the `args` changes.
As for passing paths to `@tracked`, I think someone is looking into it already.
