### ISSUE TITLE
Remove @glimmer/web-component advice for async methods

### ISSUE THREAD

**Issue by robbiepitts** [glimmerjs/glimmer-website#62]
In `tracked-properties.md`:

> Note: To get async/await to work you must create your project with the --web-component option, or add @glimmer/web-component to your package.json.

I think this is bad advice. This solves the problem by avoiding es5 compilation, which is a terribly broken thing that I think should go away (no prod builds; no minification). Also, installing a package that you don't need to alter the build pipeline in a mysterious way seems bobo to me.

I think what we _should_ be doing is recommending they install babel-polyfill, which directly solves the problem of not having `regeneratorRuntime`.

**Comment by chrishyle** [comment]
FWIW, I tried both the `--web-component` option and installing `@glimmer/web-component`, but neither "solved" this for me anyways. 

@robbiepitts - were you able to successfully get babel-polyfill to work with Glimmer? babel-polyfill internally uses `require` and just straight-up importing it (as I would in a babel project) does not seem to play well with the @glimmer/application-pipeline stuff which is using only TypeScript (AFAIK). I'm new to ember-cli, so maybe I'm missing something?

**Comment by chrishyle** [comment]
I got it to work by hacking in `"transform-regenerator"` to the *static* list in [ rollup-with-dependencies](https://github.com/glimmerjs/glimmer-application-pipeline/blob/master/lib/broccoli/rollup-with-dependencies.ts#L30-L42) and adding `import 'babel-polyfill/dist/polyfill';` to the top of my index.ts file (note the use of the dist version, to avoid the require issue).

I would take this further, but it looks like people with more experience in this have noticed that the static approach in rollup-with-dependencies.ts is not correct/scalable: https://github.com/glimmerjs/glimmer-application-pipeline/pull/19 removes it entirely. I assume the PR will also move configuration of babel more towards the [`ember-cli-build.js` approach](https://github.com/glimmerjs/glimmer-component/issues/41#issuecomment-292646619), but there is no description and too many changes for me to dive into it right now.

**Comment by chrishyle** [comment]
Also of interest: https://github.com/glimmerjs/glimmer-application-pipeline/issues/83

**Comment by robbiepitts** [comment]
@chrishyle `--web-component` is no longer a hack that works for async/await. We've removed that "feature".

We need to do something about this part of the docs. We now have no good recommendation for getting async/await to work but we're talking about using it.

**Comment by joelbowen** [comment]
Came here to learn glimmer, started watching the getting started video, ended up here... I agree with @robbiepitts.

**Comment by jenweber** [comment]
@robbiepitts @locks I walked through a temporary fix earlier with @rwjblue after running into this problem myself and finding 5+ unsolved issues about it. I can help with one of the following:
- pulling async/await out of the guide entirely
- documenting the workaround described in my PR here https://github.com/glimmerjs/glimmer-application-pipeline/pull/108

What do you think?

**Comment by robbiepitts** [comment]
@jenweber I think I like the idea of pulling async/await out of the guide. I think it is a red herring. I will defer to @locks though since I am not core.

Thanks a bunch for that PR!

**Comment by locks** [comment]
Done!
