### ISSUE TITLE
Template Guide

### ISSUE THREAD

**Issue by wycats** [glimmerjs/glimmer-website#66]
Since Glimmer has a number of extensions to vanilla Handlebars (and people might not be familiar with Handlebars anyway) that overlap but are not identical to Ember, we need a templating guide focused on how to understand Glimmer templates.

Some notable examples of extension syntax:

- [x] `@`-syntax (and the relationship to `this.args` in component classes)
- [ ] `{{yield}}`
- [ ] `{{has-block}}` (and lesser priority `{{has-block-params}}`)
- [ ] inline `if`
- [ ] `<angle-bracket>` invocation
- [ ] `{{action}}`
- [ ] "contextual components"
- [ ] attributes in HTML

**Comment by wycats** [comment]
I'd like it if we were careful to use simple language in this guide rather than terminology like "closure action" and "contextual component" :smile:

**Comment by locks** [comment]
Small note: we'll need to implement contextual components first.

**Comment by jenweber** [comment]
I wrote this [Glimmer syntax cheat sheet](https://medium.com/@jenweber/glimmer-2-cheatsheet-templates-and-cli-commands-913fe1c71612?source=linkShare-bbfa056dba1d-1506347683) a while back. Might be a good start.
