### ISSUE TITLE
Ember CLI Canary Confusion

### ISSUE THREAD

**Issue by XaserAcheron** [glimmerjs/glimmer-website#70]
This is a bit of a super-nitpick, but there's a part on the "Installing" page that makes my brain skip a beat.

The page (rather clearly) explains we need a Canary version of Ember CLI for Glimmer, and walks us through the process of installing it, like so:

> To install Ember CLI Canary, run the following command...

So far, so good. But then we get to the bottom of the page and read this:

> Ember CLI doesn't have the concept of Canary versions...

It doesn't? Then what did I just install? 😕 

[I imagine this is one of those cases where the wording is technically correct and accurate to what's actually going on, but it's really confusing from a "user" perspective.]

**Comment by locks** [comment]
Yeah, I meant that Ember CLI never has a `canary` version string, it'll be either beta, or release.
This has since been fixed, as the feature we need to use npm blueprints is in beta now :)
Thanks for reporting and for checking out Glimmerjs!
