### ISSUE TITLE
For #each iteration, how do I access the index in the loop?

### ISSUE THREAD

**Issue by li-mseritan** [glimmerjs/glimmer-website#78]
In glimmer's #each block how do I access the index of the item? I believe that in full handlebars/ember this is `@index`?

Many thanks.

**Comment by rwjblue** [comment]
You would use a second block param. 

In Ember:

`{{#each items as |item index|}}{{/each}}`

In Glimmer stand alone:

`{{#each items key="someProp" as |item index|}}{{/each}}`

**Comment by li-mseritan** [comment]
Ah yes, many thanks @rwjblue and @locks

**Comment by locks** [comment]
On behalf of @rwjblue, you're welcome ;)
