### ISSUE TITLE
each-in or... how to iterate over an object...

### ISSUE THREAD

**Issue by forbesmyester** [glimmerjs/glimmer-website#79]
Spent ages trying to figure this out... someone somewhere said `{{each-in` would work, but it doesn't appear to be implemented :-(

Maybe this is known for people who are coming with an Ember background, I do not have an Ember background. It also doesn't appear to be documented anywhere.

**Comment by locks** [comment]
Hey there :)
At the moment there is indeed no `each-in` helper. One suggestion I have to go around this problem for now is to create a `to-array` helper which converts the object to a nested array.
It would go something like this:

```
// helper.ts

export default function toArray([obj]) {
    let keys = Object.keys(obj);

    return keys.reduce((collection, key) => {
        let value = obj[key];
        return [...collection, { key, value }]
    }, [])
};
```

```
   <!-- template.hbs -->

    {{#each (to-array obj) key="key" as |item|}}
      <li>
        {{item.key}} - {{item.value}}
      </li>
    {{/each}}
```

**Comment by forbesmyester** [comment]
Thanks, seems good, but where would one put `helper.js`?

**Comment by locks** [comment]
If you do `ember g glimmer-helper to-array` at the root of your Glimmer project you should see the file being generated.
I'm closing this issue as it's still a matter of the implementation not existing, and not lack of documentation. I have opened a follow up implementation issue so we can keep track of it!

Great to hear the project is reaching non-Ember people, hope you stick around :)
