### ISSUE TITLE
Getting the index when #each of an array

### ISSUE THREAD

**Issue by forbesmyester** [glimmerjs/glimmer-website#80]
Hi,

I expected to find how to do this in the docs or at least be told you cannot do this...

```
{{#each the array key="@index" as |item|}
{{@index}}}
{{#each}}
}```

Does not work, perhaps it is not meant to... But it seems perfectly reasonable to want to be able to reference an item in an array by a position, rather than having to `find()` or `filter()` on an artificially added property of that item.

**Comment by forbesmyester** [comment]
Apologies for bad code formatting, on train on phone... no laptop accessible right now so cannot fix

**Comment by locks** [comment]
I have hopefully provided an answer in the referenced PR, I'll see you there!

**Comment by forbesmyester** [comment]
Awesome, thanks so much for your help, you're very efficient!
