### ISSUE TITLE
Interest in having a tutorial similar to what's on https://guides.emberjs.com?

### ISSUE THREAD

**Issue by ryhinchey** [glimmerjs/glimmer-website#94]
Hi There!  As a newcomer to Ember, I found the Ember Tutorial quite helpful.  I'm wondering if there's any interest in having a similar tutorial written using Glimmer?  I'd be happy to jumpstart it if there is.

The sections could be something like:

- Brief Introduction to Typescript (https://github.com/glimmerjs/glimmer-website/issues/65)
- Creating Your Glimmer App
- Planning Your App
- Build a modal component that shows a property detail view
- Build a component to filter properties
- Deploying (http://rwjblue.com/2017/04/18/deploying-glimmer-apps/)

**Comment by locks** [comment]
@ryhinchey hey, do you still have some spare cycles? :)
We could definitely start with a TypeScript primer in the current Guides.
