### ISSUE TITLE
Document Glimmer.JS browser support 

### ISSUE THREAD

**Issue by acorncom** [glimmerjs/glimmer-website#96]
Per @rwjblue in https://github.com/glimmerjs/glimmer.js/issues/8#issuecomment-336762206, he thought Glimmer was only supposed to support the browsers in the default `targets.js` file
https://github.com/glimmerjs/glimmer-blueprint/blob/master/files/config/targets.js

It would be good to document that on the website somewhere so folks know what to expect when using Glimmer ...

**Comment by rwjblue** [comment]
Thanks for creating an issue to track this!
