### ISSUE TITLE
Configuration Guide Wrong Script Name

### ISSUE THREAD

**Issue by atrama** [glimmerjs/glimmer-website#98]
`<script src="my-new-container-name.js"></script>` should be `<script src="conference-speaker.js"></script>`.

Guides also state that you need to wrap components in a containing element, which is not necessary.

I can make these changes and submit a PR.

**Comment by acorncom** [comment]
@atrama Would you mind send those changes in in separate PRs?  The containing element change is brand new, I *believe* it's shipped though ... 😀

**Comment by atrama** [comment]
@acorncom I can do that, but can you clarify which change you're referring to? I'm referring to the sentence in https://glimmerjs.com/guides/configuration that states custom elements must be wrapped, but the example does not wrap them, so there's a disconnect there. I'm assuming they still do not need wrapped, right? 

![image](https://user-images.githubusercontent.com/1631426/32064419-a732b54e-ba2e-11e7-913d-e8e2a0eeab95.png)
